baseURL: "https://josephrodvar.github.io" 
title: Joseph Rodriguez
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Data
          url: data/
          weight: 4 
        - name: Papers
          url: papers/
          weight: 2
        # - name: Books
        #   url: books/
        #   weight: 5 
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Joseph Rodriguez's data, papers, and posts on transit data"
    author: Joseph Rodriguez
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["books","courses","papers","data"]
    MainSections: ["posts","data",  "papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joseph Rodriguez
          subtitle: "I'm a transit data enthusiast!"
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Data
              url: data/
            - name: Posts
              url: posts/
            - name: Papers
              url: papers/
            - name: Tags
              url: tags/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:joseph.rodriguez.v@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=pfrkREAAAAAJ
        - name: GitHub
          url: https://github.com/josephrodvar
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joseph Rodriguez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2