baseURL: "https://josephrodvar.github.io" 
title: Joseph Rodriguez
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Data
          url: data/
          weight: 4 
        - name: Papers
          url: papers/
          weight: 2

params:
    description: "This website hosts Joseph Rodriguez's data, papers, and posts on transit data"
    author: Joseph Rodriguez
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["posts","data",  "papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joseph Rodriguez
          subtitle: "Mining data for stories about transit and cities."
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Posts
              url: posts/
            - name: Data
              url: data/
            - name: Papers
              url: papers/
            - name: Tags
              url: tags/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:joseph.rodriguez.v@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=pfrkREAAAAAJ
        - name: GitHub
          url: https://github.com/josephrodvar

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joseph Rodriguez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2